Minor refactoring
Fuco1/smartparens pull request #1066
Opened 2021-01-05 07:09 UTC by sirikid

2021-01-05 10:46 UTC, Fuco1 requested changes

2021-01-05 10:46 UTC, Fuco1 commented on smartparens.el
> +    (-when-let [(first-item rest-items) (sp-get-list-items)]
This binds the first two items, not the first and the rest.  For that the pattern has to be `(first-item . rest-items)`.

2021-01-05 10:51 UTC, Fuco1 commented
Thanks for taking the iniciative @sirikid.  Unfortunatelly I can't accept all these changes as we have a soft policy of not using cl-lib.

2021-01-05 11:01 UTC, sirikid commented
> we have a soft policy of not using cl-lib.

I'm afraid you are already using it, or is this a rule for new code?

2021-01-05 11:30 UTC, Fuco1 commented
It's sometimes accepted with new features if they use it extensively (if not we try to avoid it), but refactoring existing code to use cl would not fall under this category.

I'm not sure if this is documented anywhere and it's probably a bit frustrating.  I'll try to add it somewhere to the contribution notes.

2021-01-05 11:55 UTC, sirikid commented
I don't like `cl-loop` either, but there is no other way to work with plists.

I could write something like this, but it will take the reader a while to realize that I am actually going through the plist.
```elisp
(defun sp--merge-pairs (old-pair new-pair)
  (let ((it new-pair) prop)
    (while it
      (setq prop (pop it))
      (pop it) ;; skip value
      (sp--merge-prop prop new-pair old-pair)))
  old-pair)

(defun sp--update-pair (new-pair old-pair)
  (let ((it new-pair) prop val)
    (while it
      (setq prop (pop it)
            val (pop it))
      (unless (and (plist-get old-pair prop)
                   (equal '(:add) val))
        (plist-put old-pair prop val))))
  old-pair)
```

2021-02-12 13:33 UTC, sirikid commented
@Fuco1 could you take another look? This time I tried using "sp code style". There is still one new cl-case,  but if you are totally against it, I can switch it back to cond.

2021-02-12 14:43 UTC, Fuco1 commented on smartparens.el
> +      ((nil) pair)
Is this matching `nil` or `(nil)`, these are not the same!

2021-02-12 14:43 UTC, Fuco1 commented on smartparens.el
> -        (unless (-find-indices (lambda (it) (eq (car it) 'smartparens-strict-mode)) minor-mode-overriding-map-alist)
Isn't this the same as `(assoc 'smartparens-strict-mode minor-mode-overriding-map-alist)`.  I think we're both overcomplicating it.

2021-02-12 14:43 UTC, Fuco1 commented
@sirikid Thanks, these changes look very good.  I just have some additional questions, see the review.

2021-02-12 15:17 UTC, sirikid commented on smartparens.el
> +      ((nil) pair)
This is matching `nil`. You can't use short form (single symbol) for `nil` because it's also a list on itself.

2021-02-12 15:24 UTC, sirikid commented on smartparens.el
> -        (unless (-find-indices (lambda (it) (eq (car it) 'smartparens-strict-mode)) minor-mode-overriding-map-alist)
Even `assq`.

2021-02-12 15:49 UTC, sirikid commented on smartparens.el
> -        (unless (-find-indices (lambda (it) (eq (car it) 'smartparens-strict-mode)) minor-mode-overriding-map-alist)
I think `alist-get` would be ideal, but it was added in 25.1
```elisp
;; add 
(setf (alist-get 'smartparens-strict-mode minor-mode-overriding-map-alist)
      smartparens-strict-mode-map)
;; remove
(setf (alist-get 'smartparens-strict-mode minor-mode-overriding-map-alist nil t)
      nil)
````

2021-02-13 18:50 UTC, Fuco1 commented on smartparens.el
> +      ((nil) pair)
Oh, good to know, I'm not a huge `cl-case` user. :+1:

2021-02-13 18:51 UTC, merged

2021-02-13 18:51 UTC, Fuco1 commented
Thanks for the improvements!

2021-02-15 17:09 UTC, bymoz089 commented
this merge introduces a bug, see #1077

2021-02-15 17:25 UTC, manuel-uberti commented
Could it be a slip because of too much Clojure programming? :)

2021-02-15 17:59 UTC, sirikid commented
> Could it be a slip because of too much Clojure programming? :)

This is because dash is inconsistent and has different rules for `-let` and `-when-let`

2021-02-16 08:54 UTC, manuel-uberti commented
> > Could it be a slip because of too much Clojure programming? :)
> 
> This is because dash is inconsistent and has different rules for `-let` and `-when-let`

As I said [here](https://github.com/Fuco1/smartparens/issues/1077#issuecomment-779683117), isn't `when-let` already available in Emacs? Does the `dash` version offer a better implementation?

2021-02-16 10:38 UTC, sirikid commented
> Does the `dash` version offer a better implementation?

It also offers destructuring.

2021-03-01 12:34 UTC, duianto commented
There's a PR pending with a fix: [Fix #1077 #1079](https://github.com/Fuco1/smartparens/pull/1079)
for:
>Eager macro-expansion failure: (wrong-type-argument listp [(first-item . rest-items) (sp-get-list-items)])

2021-03-29 10:00 UTC, duianto commented
The PR has been merged, the error message doesn't appear anymore.