Support `ruby-ts-mode`
Fuco1/smartparens pull request #1162
Opened 2023-05-11 15:23 UTC by danielma

As of Emacs 29, `ruby-mode` and `ruby-ts-mode` are derived from `ruby-base-mode`. Have smartparens define behavior from the base mode to work with both

2023-05-29 09:36 UTC, Fuco1 commented
This is a bit surprising but inheritance actually does not work everywhere in smartparens.  I don't remember if this was a conscious decision (probably wasn't) and I think it should be fixed.  But for now, your patch would not work.

Where it does work is pair configuration.

2023-05-29 09:37 UTC, Fuco1 requested changes

2023-05-29 09:37 UTC, Fuco1 commented on smartparens-ruby.el
> +             '((ruby-base-mode enh-ruby-mode motion-mode) . sp--ruby-skip-match))
Here inheritance does not work so you need to mention each mode separately.

2023-05-29 09:37 UTC, Fuco1 commented on smartparens-ruby.el
> +(dolist (mode '(ruby-base-mode motion-mode))
Here inheritance does not work so you need to mention each mode separately.

2023-05-30 23:33 UTC, danielma commented
@Fuco1 Thank you for the feedback! That does surprise me, and it seemed to work correctly for me locally, but I've fixed it now.

It was very helpful of you to point out the specific places I needed to change

2023-10-20 15:58 UTC, Fuco1 approved these changes

2023-10-20 15:58 UTC, merged

2023-10-20 15:58 UTC, Fuco1 commented
Sorry for taking so long to merge this :blush: