Add support for js-ts-mode and typescript-ts-mode
Fuco1/smartparens pull request #1174
Opened 2023-10-21 18:53 UTC by akreisher

Adds the new Emacs 29+ `js-ts-mode` and `typescript/tsx-ts-mode` to the configs for `smartparent-javascript`. 

I also added `tsx-ts-mode` to `sp--html-modes` which  should address https://github.com/Fuco1/smartparens/issues/1168.

2023-10-23 13:10 UTC, Fuco1 requested changes

2023-10-23 13:10 UTC, Fuco1 commented on smartparens-config.el
> +(--each '(js js2-mode typescript-ts-mode)
we should probably add `js-ts-mode` here as well then? Since you added it to the config.

2023-10-23 15:56 UTC, akreisher commented on smartparens-config.el
> +(--each '(js js2-mode typescript-ts-mode)
`js-ts-mode` is provided in `js.el`, so I believe just including `js` here should be sufficient for both `js-mode` and `js-ts-mode` (since I believe this form expects package names for `use-after-load`, not mode symbols). `typescript-ts-mode` on the other hand is in its own package (`typescript-ts-mode.el`) and so needs its own entry here.

I believe the same applies for python. This line:
https://github.com/fuco1/smartparens/blob/96fccc0816093aaad4b904a20802ec306c6da420/smartparens-config.el#L135-L136

could probably just be:

```
(eval-after-load 'python                   '(require 'smartparens-python))
```
since both `python-mode` and `python-ts-mode` are defined in `python.el`.

2023-10-24 18:04 UTC, Fuco1 commented on smartparens-config.el
> +(--each '(js js2-mode typescript-ts-mode)
right, good catch!

2023-10-24 18:04 UTC, merged

2023-10-24 18:04 UTC, Fuco1 commented
Thanks!