Add support for clojure-ts-mode (and its derived modes)
Fuco1/smartparens pull request #1185
Opened 2024-02-04 15:54 UTC by kommen

[`clojure-ts-mode`](https://github.com/clojure-emacs/clojure-ts-mode)  is developed as a distinct alternative to `clojure-mode`, as discussed here: https://github.com/clojure-emacs/clojure-mode/issues/640#issuecomment-1359708131

2024-02-13 07:10 UTC, kommen commented
Marking as draft until this is resolved: https://github.com/clojure-emacs/clojure-ts-mode/pull/36

2024-02-13 07:55 UTC, bbatsov commented
Hmm, do we even need to iterate the derived modes if there's no special smartparens configuration for them? Seems excessive to me. Perhaps the legacy config is from the days before all modes were folded in `clojure-mode`?

2024-02-13 13:41 UTC, kommen commented
@bbatsov thanks for the feedback. I can give it a try in the next days without all the derived modes.

2024-02-13 21:32 UTC, kommen commented
I removed all the derived modes. As far as I can tell, everything works fine in buffers using the derived modes.

2024-03-17 20:52 UTC, Fuco1 requested changes

2024-03-17 20:52 UTC, Fuco1 commented on smartparens.el
> -                           clojurex-mode
This needs to stay there because `sp-list-modes` is checked literally not taking into account how modes derive from one another.

The question is whether it should, but right now it doesn't, so this will actually remove these modes from being marked as "lisp" modes.

2024-03-17 20:52 UTC, Fuco1 commented on smartparens-clojure.el
> -(dolist (mode '(clojure-mode clojurescript-mode clojurec-mode cider-repl-mode))
This `sp-sexp-prefix` setting takes the modes literally, not taking into account how modes derive from one another.  So removing them here will break things unfortunatelly.

2024-04-21 19:53 UTC, kommen commented
@Fuco1 I have reverted the commit which removed the modes from the lists. Would you prefer me to force push it out?

2024-06-29 13:15 UTC, Fuco1 commented
I rebased these commits to master and merged them separately.  Sorry it took me so long.  I will close this pull request but don't worry as the changes made it in.

Thanks!

2024-06-29 13:15 UTC, closed without merging

2024-06-29 13:39 UTC, kommen commented
@Fuco1 Thank you so much for your work and again for your feedback!